import streamlit as st

st.set_page_config(page_title="KitchenSync", page_icon="🍳")

st.title("🍳 KitchenSync")
st.subheader("Your Intelligent Meal & Pantry Coordinator")

# Simple input for the MVP
meal_choice = st.text_input("What are we eating this week?", "Chicken and Broccoli Stir Fry")

if st.button("Sync to Cart"):
    st.write(f"Analyzing ingredients for: **{meal_choice}**...")
    
    # In the future, this list will be generated by the Gemini API
    # For now, we are simulating the 'mapped' items from Walmart
    items = [
        {"name": "Great Value Chicken Breast", "id": "27935840", "qty": 1},
        {"name": "Fresh Broccoli Florets", "id": "51259378", "qty": 2}
    ]
    
    # Generate the Walmart Cart URL
    base_url = "https://www.walmart.com/cart/add?items="
    item_strings = [f"{item['id']}:{item['qty']}" for item in items]
    final_url = base_url + ",".join(item_strings)
    
    st.success("Shopping list generated!")
    st.link_button("🛒 Add to Walmart Cart", final_url)
    
    st.write("---")
    st.caption("KitchenSync v0.1 | Powered by AI")
